import { beforeEach, describe, expect, it, vi } from 'vitest';
const db={addSong:vi.fn(),deleteSong:vi.fn()};const fsApi={copy:vi.fn()};const pathApi={extname:vi.fn(),join:vi.fn(),parse:vi.fn()};const store={get:vi.fn()};const toast=vi.fn();
vi.mock('../../../src/renderer/modules/adapters/secure-adapter.js',()=>({secureDatabase:db,secureFileSystem:fsApi,securePath:pathApi,secureStore:store}));vi.mock('../../../src/renderer/modules/categories/category-data.js',()=>({populateCategorySelect:vi.fn(async()=>{}),getCategoryDescription:x=>x}));vi.mock('../../../src/renderer/modules/ui/bootstrap-helpers.js',()=>({safeShowModal:vi.fn(),safeHideModal:vi.fn()}));vi.mock('../../../src/renderer/modules/drag-drop/drag-drop-functions.js',()=>({songDrag:vi.fn()}));vi.mock('../../../src/renderer/modules/utils/toast-utils.js',()=>({showDropToast:toast}));
function control(){return{value:'',classList:{add:vi.fn(),remove:vi.fn()},focus:vi.fn(),scrollIntoView:vi.fn()};}function row(){const controls={'.song-title-input':control(),'.song-artist-input':control(),'.song-info-input':control(),'.song-category-select':control()};return{dataset:{},style:{},classList:{},querySelector:s=>controls[s],appendChild:vi.fn(),setAttribute:vi.fn(),addEventListener:vi.fn()};}
const list={children:[],innerHTML:'',appendChild(x){this.children.push(x);},querySelectorAll:()=>list.children,querySelector:()=>null};const count=control(),globalCat=control(),submit={disabled:false,innerHTML:'',textContent:''},results={style:{},appendChild:vi.fn(),querySelectorAll:()=>[]};
globalThis.alert=vi.fn();globalThis.window={debugLog:{info:vi.fn(),warn:vi.fn(),error:vi.fn()},secureElectronAPI:{utils:{generateId:vi.fn()},analytics:{trackEvent:vi.fn()}}};globalThis.document={getElementById:id=>({'multi-song-import-list':list,'multi-song-import-count':count,'multi-import-global-category':globalCat,'multiSongImportSubmitButton':submit}[id]||null),createElement:tag=>tag==='div'?row():row(),querySelector:s=>s.includes('search_results')?results:null};
const multi=await import('../../../src/renderer/modules/bulk-operations/multi-song-import.js');
describe('multi-song partial failure handling',()=>{beforeEach(()=>{vi.clearAllMocks();list.children=[];db.addSong.mockResolvedValueOnce({success:true,data:{lastInsertRowid:1}}).mockResolvedValueOnce({success:true,data:{lastInsertRowid:2}});db.deleteSong.mockResolvedValue({success:true});fsApi.copy.mockResolvedValueOnce({success:false,error:'disk full'}).mockResolvedValueOnce({success:true});pathApi.extname.mockResolvedValue({success:true,data:'.mp3'});pathApi.join.mockResolvedValue({success:true,data:'/music/song.mp3'});store.get.mockResolvedValue({success:true,value:'/music'});window.secureElectronAPI.utils.generateId.mockResolvedValue({success:true,data:'id'});});
it('rolls back failed copies and reports only successful imports',async()=>{await multi.showMultiSongImport([{filePath:'/a.mp3',title:'A',category:'MUSC'},{filePath:'/b.mp3',title:'B',category:'MUSC'}]);await multi.saveMultiSongImport();expect(alert).not.toHaveBeenCalled();expect(db.deleteSong).toHaveBeenCalledWith(1);expect(results.appendChild).toHaveBeenCalledTimes(1);expect(toast).toHaveBeenCalledWith('Successfully imported 1 song');});});
