version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: music-metadata
    versions:
    - 7.6.8
    - 7.8.4
    - 7.8.5
  - dependency-name: electron-log
    versions:
    - 4.3.3
    - 4.3.4
