version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "10:00"
  groups:
    weekly-batch:
      patterns:
      - "*"
  cooldown:
    default-days: 3
  versioning-strategy: increase
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: music-metadata
    versions:
    - 7.6.8
    - 7.8.4
    - 7.8.5
  - dependency-name: electron-log
    versions:
    - 4.3.3
    - 4.3.4
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "10:00"
  groups:
    weekly-batch:
      patterns:
      - "*"
  cooldown:
    default-days: 3
