import { beforeEach, describe, expect, it, vi } from 'vitest';
const handlers={}; const ipcMain={handle:(name,fn)=>{handlers[name]=fn;}}; const windows=[];
class BrowserWindow { constructor(options){this.options=options;this.loadFile=vi.fn(async()=>{});this.focus=vi.fn();this.close=vi.fn();this.on=vi.fn((name,fn)=>{this[name]=fn;});this.webContents={};windows.push(this);} }
vi.mock('electron',()=>({default:{BrowserWindow,ipcMain,app:{quit:vi.fn()}}}));
const launcher=await import('../../../src/main/modules/launcher-window.js');
const profiles={getAvailableProfiles:vi.fn(),createProfile:vi.fn(),deleteProfile:vi.fn(),updateProfileLastUsed:vi.fn()}; const launch=vi.fn();
describe('launcher window contracts',()=>{beforeEach(()=>{vi.clearAllMocks();launcher.closeLauncherWindow();launcher.initializeLauncherWindow({debugLog:{info:vi.fn(),error:vi.fn()},profileManager:profiles,mainAppLauncher:launch,store:{get:vi.fn(),delete:vi.fn()},mainWindow:null});});
it('creates a context-isolated hidden test window and reuses it',async()=>{process.env.APP_TEST_MODE='1';const first=await launcher.createLauncherWindow();const second=await launcher.createLauncherWindow();expect(first).toBe(second);expect(first.options.webPreferences).toMatchObject({nodeIntegration:false,contextIsolation:true});expect(first.options.show).toBe(false);expect(first.focus).toHaveBeenCalled();});
it('wraps profile handlers and launcher failures',async()=>{profiles.getAvailableProfiles.mockResolvedValue([{name:'Default User'}]);await expect(handlers['launcher:get-profiles']()).resolves.toMatchObject({success:true,profiles:[{name:'Default User'}]});profiles.createProfile.mockRejectedValue(new Error('disk'));await expect(handlers['launcher:create-profile']({},'New','')).resolves.toEqual({success:false,error:'disk'});});
it('launches the selected profile and updates last-used state',async()=>{vi.useFakeTimers();launch.mockResolvedValue();await expect(handlers['launcher:launch-app']({},'Show')).resolves.toEqual({success:true});expect(profiles.updateProfileLastUsed).toHaveBeenCalledWith('Show');expect(launch).toHaveBeenCalledWith('Show');await vi.runAllTimersAsync();vi.useRealTimers();});});
